import type { ComponentType } from "react";
import type { IconComponentProps } from "./icon-provider";
import * as icons from "./icons";

/**
 * Maps string names to built-in SVG icon components.
 * Supports both spark-ui names (kebab-case) and Material Symbols names (snake_case).
 */
const builtInIcons: Record<string, ComponentType<IconComponentProps>> = {
  // ── Navigation ──
  "chevron-left": icons.ChevronLeftIcon,
  "chevron_left": icons.ChevronLeftIcon,
  "chevron-right": icons.ChevronRightIcon,
  "chevron_right": icons.ChevronRightIcon,
  "chevron-down": icons.ChevronDownIcon,
  "chevron_down": icons.ChevronDownIcon,
  "expand_more": icons.ChevronDownIcon,
  "chevron-up": icons.ChevronUpIcon,
  "chevron_up": icons.ChevronUpIcon,
  "expand_less": icons.ChevronUpIcon,
  "chevrons-left": icons.ChevronsLeftIcon,
  "chevrons_left": icons.ChevronsLeftIcon,
  "first-page": icons.ChevronsLeftIcon,
  "first_page": icons.ChevronsLeftIcon,
  "chevrons-right": icons.ChevronsRightIcon,
  "chevrons_right": icons.ChevronsRightIcon,
  "last-page": icons.ChevronsRightIcon,
  "last_page": icons.ChevronsRightIcon,
  "chevrons-up-down": icons.ChevronsUpDownIcon,
  "chevrons_up_down": icons.ChevronsUpDownIcon,
  "unfold_more": icons.ChevronsUpDownIcon,
  "arrow-left": icons.ArrowLeftIcon,
  "arrow_left": icons.ArrowLeftIcon,
  "arrow-right": icons.ArrowRightIcon,
  "arrow_right": icons.ArrowRightIcon,
  "arrow_forward": icons.ArrowRightIcon,
  "arrow-up": icons.ArrowUpIcon,
  "arrow_up": icons.ArrowUpIcon,
  "arrow-down": icons.ArrowDownIcon,
  "arrow_down": icons.ArrowDownIcon,
  "external-link": icons.ExternalLinkIcon,
  "navigation": icons.NavigationIcon,

  // ── Actions ──
  "close": icons.CloseIcon,
  "x": icons.CloseIcon,
  "plus": icons.PlusIcon,
  "add": icons.PlusIcon,
  "minus": icons.MinusIcon,
  "check": icons.CheckIcon,
  "search": icons.SearchIcon,
  "edit": icons.EditIcon,
  "trash": icons.TrashIcon,
  "delete": icons.TrashIcon,
  "copy": icons.CopyIcon,
  "download": icons.DownloadIcon,
  "upload": icons.UploadIcon,
  "cloud_upload": icons.UploadIcon,
  "filter": icons.FilterIcon,
  "tune": icons.FilterIcon,
  "settings": icons.SettingsIcon,
  "settings-gear": icons.SettingsGearIcon,
  "more-horizontal": icons.MoreHorizontalIcon,
  "more_horiz": icons.MoreHorizontalIcon,
  "more-vertical": icons.MoreVerticalIcon,
  "more_vert": icons.MoreVerticalIcon,
  "refresh": icons.RefreshCwIcon,
  "refresh-cw": icons.RefreshCwIcon,
  "rotate-ccw": icons.RotateCcwIcon,
  "save": icons.SaveIcon,
  "scissors": icons.ScissorsIcon,
  "crop": icons.CropIcon,

  // ── Status ──
  "check-circle": icons.CheckCircleIcon,
  "check_circle": icons.CheckCircleIcon,
  "alert-circle": icons.AlertCircleIcon,
  "error": icons.AlertCircleIcon,
  "alert-triangle": icons.AlertTriangleIcon,
  "warning": icons.AlertTriangleIcon,
  "info": icons.InfoIcon,
  "x-circle": icons.XCircleIcon,
  "help-circle": icons.HelpCircleIcon,
  "plus-circle": icons.PlusCircleIcon,
  "minus-circle": icons.MinusCircleIcon,
  "slash": icons.SlashIcon,

  // ── Communication ──
  "phone": icons.PhoneIcon,
  "phone-off": icons.PhoneOffIcon,
  "message-square": icons.MessageSquareIcon,
  "message-circle": icons.MessageCircleIcon,
  "send": icons.SendIcon,
  "inbox": icons.InboxIcon,
  "at-sign": icons.AtSignIcon,
  "mail": icons.MailIcon,

  // ── Media ──
  "play": icons.PlayIcon,
  "pause": icons.PauseIcon,
  "stop-circle": icons.StopCircleIcon,
  "skip-forward": icons.SkipForwardIcon,
  "skip-back": icons.SkipBackIcon,
  "volume": icons.VolumeIcon,
  "volume-1": icons.Volume1Icon,
  "volume-2": icons.Volume2Icon,
  "volume-x": icons.VolumeXIcon,
  "mic": icons.MicIcon,
  "mic-off": icons.MicOffIcon,
  "video": icons.VideoIcon,
  "camera": icons.CameraIcon,
  "music": icons.MusicIcon,
  "image": icons.ImageIcon,

  // ── Files ──
  "file": icons.FileIcon,
  "file-text": icons.FileTextIcon,
  "file-plus": icons.FilePlusIcon,
  "folder": icons.FolderIcon,
  "folder-open": icons.FolderOpenIcon,
  "clipboard": icons.ClipboardIcon,
  "archive": icons.ArchiveIcon,
  "paperclip": icons.PaperclipIcon,
  "link": icons.LinkIcon,

  // ── Layout ──
  "menu": icons.MenuIcon,
  "grip-vertical": icons.GripVerticalIcon,
  "grip_vertical": icons.GripVerticalIcon,
  "drag_indicator": icons.GripVerticalIcon,
  "grid": icons.GridIcon,
  "list": icons.ListIcon,
  "columns": icons.ColumnsIcon,
  "sidebar": icons.SidebarIcon,
  "maximize": icons.MaximizeIcon,
  "minimize": icons.MinimizeIcon,
  "layers": icons.LayersIcon,

  // ── Commerce ──
  "shopping-cart": icons.ShoppingCartIcon,
  "shopping-bag": icons.ShoppingBagIcon,
  "credit-card": icons.CreditCardIcon,
  "dollar-sign": icons.DollarSignIcon,
  "gift": icons.GiftIcon,
  "percent": icons.PercentIcon,
  "tag": icons.TagIcon,

  // ── Maps ──
  "map-pin": icons.MapPinIcon,
  "map": icons.MapIcon,
  "compass": icons.CompassIcon,

  // ── Devices ──
  "smartphone": icons.SmartphoneIcon,
  "tablet": icons.TabletIcon,
  "monitor": icons.MonitorIcon,
  "laptop": icons.LaptopIcon,
  "printer": icons.PrinterIcon,

  // ── Security ──
  "lock": icons.LockIcon,
  "unlock": icons.UnlockIcon,
  "shield": icons.ShieldIcon,
  "shield-check": icons.ShieldCheckIcon,
  "key": icons.KeyIcon,
  "fingerprint": icons.FingerprintIcon,

  // ── Data ──
  "bar-chart": icons.BarChartIcon,
  "pie-chart": icons.PieChartIcon,
  "trending-up": icons.TrendingUpIcon,
  "trending-down": icons.TrendingDownIcon,
  "activity": icons.ActivityIcon,
  "database": icons.DatabaseIcon,
  "server": icons.ServerIcon,
  "hash": icons.HashIcon,

  // ── Formatting ──
  "bold": icons.BoldIcon,
  "italic": icons.ItalicIcon,
  "underline": icons.UnderlineIcon,
  "align-left": icons.AlignLeftIcon,
  "align-center": icons.AlignCenterIcon,
  "align-right": icons.AlignRightIcon,
  "type": icons.TypeIcon,

  // ── Social ──
  "share": icons.ShareIcon,
  "share-2": icons.Share2Icon,
  "thumbs-up": icons.ThumbsUpIcon,
  "thumbs-down": icons.ThumbsDownIcon,
  "bookmark": icons.BookmarkIcon,
  "flag": icons.FlagIcon,
  "award": icons.AwardIcon,

  // ── UI ──
  "calendar": icons.CalendarIcon,
  "calendar_today": icons.CalendarIcon,
  "eye": icons.EyeIcon,
  "visibility": icons.EyeIcon,
  "eye-off": icons.EyeOffIcon,
  "visibility_off": icons.EyeOffIcon,
  "home": icons.HomeIcon,
  "user": icons.UserIcon,
  "users": icons.UsersIcon,
  "user-plus": icons.UserPlusIcon,
  "user-minus": icons.UserMinusIcon,
  "user-check": icons.UserCheckIcon,
  "star": icons.StarIcon,
  "heart": icons.HeartIcon,
  "bell": icons.BellIcon,
  "notifications": icons.BellIcon,
  "loader": icons.LoaderIcon,
  "log-in": icons.LogInIcon,
  "log-out": icons.LogOutIcon,
  "logout": icons.LogOutIcon,
  "code": icons.CodeIcon,
  "terminal": icons.TerminalIcon,
  "target": icons.TargetIcon,
  "crosshair": icons.CrosshairIcon,
  "anchor": icons.AnchorIcon,
  "life-buoy": icons.LifeBuoyIcon,
  "sparkles": icons.SparklesIcon,

  // ── Weather ──
  "cloud": icons.CloudIcon,
  "cloud-rain": icons.CloudRainIcon,
  "thermometer": icons.ThermometerIcon,
  "wind": icons.WindIcon,
  "droplet": icons.DropletIcon,
  "sun": icons.SunIcon,
  "light_mode": icons.SunIcon,
  "moon": icons.MoonIcon,
  "dark_mode": icons.MoonIcon,

  // ── Time ──
  "clock": icons.ClockIcon,
  "watch": icons.WatchIcon,
  "timer": icons.TimerIcon,

  // ── Misc ──
  "zap": icons.ZapIcon,
  "battery": icons.BatteryIcon,
  "wifi": icons.WifiIcon,
  "bluetooth": icons.BluetoothIcon,
  "power": icons.PowerIcon,
  "globe": icons.GlobeIcon,

  // ── Additional Actions ──
  "undo": icons.UndoIcon,
  "redo": icons.RedoIcon,
  "cut": icons.ScissorsIcon,
  "zoom-in": icons.ZoomInIcon,
  "zoom_in": icons.ZoomInIcon,
  "zoom-out": icons.ZoomOutIcon,
  "zoom_out": icons.ZoomOutIcon,
  "move": icons.MoveIcon,
  "cursor": icons.CursorIcon,
  "mouse-pointer": icons.CursorIcon,
  "list-ordered": icons.ListOrderedIcon,
  "format_list_numbered": icons.ListOrderedIcon,
  "print": icons.PrinterIcon,

  // ── Material Symbols Formatting Aliases ──
  "format-bold": icons.BoldIcon,
  "format_bold": icons.BoldIcon,
  "format-italic": icons.ItalicIcon,
  "format_italic": icons.ItalicIcon,
  "format-underline": icons.UnderlineIcon,
  "format_underline": icons.UnderlineIcon,
  "format-align-left": icons.AlignLeftIcon,
  "format_align_left": icons.AlignLeftIcon,
  "format-align-center": icons.AlignCenterIcon,
  "format_align_center": icons.AlignCenterIcon,
  "format-align-right": icons.AlignRightIcon,
  "format_align_right": icons.AlignRightIcon,

  // ── Material Symbols Misc Aliases ──
  "drafts": icons.FileTextIcon,
  "publish": icons.SendIcon,
  "schedule": icons.ClockIcon,
  "delete_forever": icons.TrashIcon,
  "picture_as_pdf": icons.FileTextIcon,
  "table_chart": icons.GridIcon,

  // ── Extended Arrows & Navigation ──
  "arrow-up-left": icons.ArrowUpLeftIcon,
  "arrow_up_left": icons.ArrowUpLeftIcon,
  "arrow-up-right": icons.ArrowUpRightIcon,
  "arrow_up_right": icons.ArrowUpRightIcon,
  "arrow-down-left": icons.ArrowDownLeftIcon,
  "arrow_down_left": icons.ArrowDownLeftIcon,
  "arrow-down-right": icons.ArrowDownRightIcon,
  "arrow_down_right": icons.ArrowDownRightIcon,
  "arrow-left-right": icons.ArrowLeftRightIcon,
  "arrow_left_right": icons.ArrowLeftRightIcon,
  "swap_horiz": icons.ArrowLeftRightIcon,
  "arrow-up-down": icons.ArrowUpDownIcon,
  "arrow_up_down": icons.ArrowUpDownIcon,
  "swap_vert": icons.ArrowUpDownIcon,
  "corner-down-left": icons.CornerDownLeftIcon,
  "corner-down-right": icons.CornerDownRightIcon,
  "corner-up-left": icons.CornerUpLeftIcon,
  "corner-up-right": icons.CornerUpRightIcon,
  "chevrons-down": icons.ChevronsDownIcon,
  "chevrons_down": icons.ChevronsDownIcon,
  "chevrons-up": icons.ChevronsUpIcon,
  "chevrons_up": icons.ChevronsUpIcon,
  "arrow-big-up": icons.ArrowBigUpIcon,
  "arrow-big-down": icons.ArrowBigDownIcon,
  "arrow-big-left": icons.ArrowBigLeftIcon,
  "arrow-big-right": icons.ArrowBigRightIcon,
  "move-horizontal": icons.MoveHorizontalIcon,
  "move-vertical": icons.MoveVerticalIcon,
  "move-diagonal": icons.MoveDiagonalIcon,
  "repeat": icons.RepeatIcon,
  "repeat-1": icons.Repeat1Icon,
  "repeat_one": icons.Repeat1Icon,

  // ── Extended Actions & Editing ──
  "paste": icons.PasteIcon,
  "content_paste": icons.PasteIcon,
  "clipboard-check": icons.ClipboardCheckIcon,
  "clipboard_check": icons.ClipboardCheckIcon,
  "assignment_turned_in": icons.ClipboardCheckIcon,
  "clipboard-copy": icons.ClipboardCopyIcon,
  "clipboard-list": icons.ClipboardListIcon,
  "clipboard_list": icons.ClipboardListIcon,
  "clipboard-x": icons.ClipboardXIcon,
  "trash-2": icons.Trash2Icon,
  "archive-restore": icons.ArchiveRestoreIcon,
  "unarchive": icons.ArchiveRestoreIcon,
  "eraser": icons.EraserIcon,
  "wand": icons.WandIcon,
  "auto_fix_high": icons.WandIcon,
  "magic-wand": icons.WandIcon,
  "pin": icons.PinIcon,
  "push_pin": icons.PinIcon,
  "pin-off": icons.PinOffIcon,
  "sort-asc": icons.SortAscIcon,
  "sort_ascending": icons.SortAscIcon,
  "sort-desc": icons.SortDescIcon,
  "sort_descending": icons.SortDescIcon,
  "arrow-down-az": icons.ArrowDownAZIcon,
  "sort_by_alpha": icons.ArrowDownAZIcon,
  "arrow-up-az": icons.ArrowUpAZIcon,

  // ── Extended Status & Feedback ──
  "ban": icons.BanIcon,
  "block": icons.BanIcon,
  "do_not_disturb": icons.BanIcon,
  "circle-alert": icons.CircleAlertIcon,
  "circle-check": icons.CircleCheckIcon,
  "task_alt": icons.CircleCheckIcon,
  "octagon-alert": icons.OctagonAlertIcon,
  "shield-alert": icons.ShieldAlertIcon,
  "shield-x": icons.ShieldXIcon,
  "check-check": icons.CheckCheckIcon,
  "done_all": icons.CheckCheckIcon,
  "circle-dot": icons.CircleDotIcon,
  "radio_button_checked": icons.CircleDotIcon,
  "circle-dashed": icons.CircleDashedIcon,
  "badge-check": icons.BadgeCheckIcon,
  "verified": icons.BadgeCheckIcon,

  // ── Bell Variants ──
  "bell-off": icons.BellOffIcon,
  "notifications_off": icons.BellOffIcon,
  "bell-ring": icons.BellRingIcon,
  "notifications_active": icons.BellRingIcon,
  "bell-dot": icons.BellDotIcon,
  "notification_important": icons.BellDotIcon,
  "bell-plus": icons.BellPlusIcon,
  "bell-minus": icons.BellMinusIcon,

  // ── Layout & Panels ──
  "panel-left": icons.PanelLeftIcon,
  "panel-left-open": icons.PanelLeftOpenIcon,
  "panel-left-close": icons.PanelLeftCloseIcon,
  "panel-right": icons.PanelRightIcon,
  "panel-right-open": icons.PanelRightOpenIcon,
  "panel-right-close": icons.PanelRightCloseIcon,
  "panel-top": icons.PanelTopIcon,
  "panel-bottom": icons.PanelBottomIcon,
  "layout-dashboard": icons.LayoutDashboardIcon,
  "dashboard": icons.LayoutDashboardIcon,
  "layout-grid": icons.LayoutGridIcon,
  "layout-list": icons.LayoutListIcon,
  "layout-template": icons.LayoutTemplateIcon,
  "kanban": icons.KanbanIcon,
  "view_kanban": icons.KanbanIcon,
  "table": icons.TableIcon,
  "table_view": icons.TableIcon,
  "sticky-note": icons.StickyNoteIcon,
  "note": icons.StickyNoteIcon,
  "grip-horizontal": icons.GripHorizontalIcon,
  "drag_handle": icons.GripHorizontalIcon,
  "separator-horizontal": icons.SeparatorHorizontalIcon,
  "separator-vertical": icons.SeparatorVerticalIcon,
  "resize": icons.ResizeIcon,
  "split": icons.SplitIcon,
  "call_split": icons.SplitIcon,
  "app-window": icons.AppWindowIcon,
  "web_asset": icons.AppWindowIcon,
  "picture-in-picture": icons.PictureInPictureIcon,
  "pip": icons.PictureInPictureIcon,

  // ── Form Controls ──
  "toggle-left": icons.ToggleLeftIcon,
  "toggle_off": icons.ToggleLeftIcon,
  "toggle-right": icons.ToggleRightIcon,
  "toggle_on": icons.ToggleRightIcon,
  "sliders-horizontal": icons.SlidersHorizontalIcon,
  "tune_horizontal": icons.SlidersHorizontalIcon,
  "sliders-vertical": icons.SlidersVerticalIcon,
  "text-cursor": icons.TextCursorIcon,
  "text-cursor-input": icons.TextCursorInputIcon,
  "square-check": icons.SquareCheckIcon,
  "check_box": icons.SquareCheckIcon,
  "list-filter": icons.ListFilterIcon,
  "filter_list": icons.ListFilterIcon,

  // ── Common Missing: General ──
  "rocket": icons.RocketIcon,
  "rocket_launch": icons.RocketIcon,
  "lightbulb": icons.LightbulbIcon,
  "light_bulb": icons.LightbulbIcon,
  "lightbulb-off": icons.LightbulbOffIcon,
  "bug": icons.BugIcon,
  "bug_report": icons.BugIcon,
  "wrench": icons.WrenchIcon,
  "build": icons.WrenchIcon,
  "hammer": icons.HammerIcon,
  "book-open": icons.BookOpenIcon,
  "menu_book": icons.BookOpenIcon,
  "book": icons.BookIcon,
  "trophy": icons.TrophyIcon,
  "emoji_events": icons.TrophyIcon,
  "crown": icons.CrownIcon,
  "flame": icons.FlameIcon,
  "fire": icons.FlameIcon,
  "local_fire_department": icons.FlameIcon,
  "briefcase": icons.BriefcaseIcon,
  "work": icons.BriefcaseIcon,
  "truck": icons.TruckIcon,
  "local_shipping": icons.TruckIcon,
  "plane": icons.PlaneIcon,
  "flight": icons.PlaneIcon,
  "car": icons.CarIcon,
  "directions_car": icons.CarIcon,
  "building": icons.BuildingIcon,
  "apartment": icons.BuildingIcon,
  "coffee": icons.CoffeeIcon,
  "local_cafe": icons.CoffeeIcon,
  "headphones": icons.HeadphonesIcon,
  "headset": icons.HeadphonesIcon,
  "keyboard": icons.KeyboardIcon,
  "mouse": icons.MouseIcon,
  "smile": icons.SmileIcon,
  "sentiment_satisfied": icons.SmileIcon,
  "frown": icons.FrownIcon,
  "sentiment_dissatisfied": icons.FrownIcon,
  "meh": icons.MehIcon,
  "sentiment_neutral": icons.MehIcon,
  "hourglass": icons.HourglassIcon,
  "hourglass_empty": icons.HourglassIcon,
  "history": icons.HistoryIcon,
  "shuffle": icons.ShuffleIcon,
  "calculator": icons.CalculatorIcon,
  "calculate": icons.CalculatorIcon,
  "qr-code": icons.QrCodeIcon,
  "qr_code": icons.QrCodeIcon,
  "wallet": icons.WalletIcon,
  "account_balance_wallet": icons.WalletIcon,
  "receipt": icons.ReceiptIcon,
  "coins": icons.CoinsIcon,
  "banknote": icons.BanknoteIcon,
  "payments": icons.BanknoteIcon,
  "scale": icons.ScaleIcon,
  "balance": icons.ScaleIcon,
  "unlink": icons.UnlinkIcon,
  "link-break": icons.LinkBreakIcon,
  "link_off": icons.UnlinkIcon,
  "accessibility": icons.AccessibilityIcon,
  "accessible": icons.AccessibilityIcon,
  "pencil": icons.PencilIcon,
  "pen": icons.PenIcon,
  "paintbrush": icons.PaintbrushIcon,
  "brush": icons.PaintbrushIcon,
  "palette": icons.PaletteIcon,
  "color_lens": icons.PaletteIcon,
  "ruler": icons.RulerIcon,
  "straighten": icons.RulerIcon,
  "graduation-cap": icons.GraduationCapIcon,
  "school": icons.GraduationCapIcon,

  // ── Connectivity & Devices ──
  "radio": icons.RadioIcon,
  "rss": icons.RssIcon,
  "rss_feed": icons.RssIcon,
  "signal": icons.SignalIcon,
  "signal_cellular_alt": icons.SignalIcon,
  "cast": icons.CastIcon,
  "screen-share": icons.ScreenShareIcon,
  "present_to_all": icons.ScreenShareIcon,
  "tv": icons.TvIcon,
  "speaker": icons.SpeakerIcon,
  "cpu": icons.CpuIcon,
  "memory": icons.CpuIcon,
  "hard-drive": icons.HardDriveIcon,
  "storage": icons.HardDriveIcon,
  "plug": icons.PlugIcon,
  "power_plug": icons.PlugIcon,
  "usb": icons.UsbIcon,
  "wifi-off": icons.WifiOffIcon,
  "wifi_off": icons.WifiOffIcon,
  "podcast": icons.PodcastIcon,
  "podcasts": icons.PodcastIcon,
  "router": icons.RouterIcon,

  // ── Weather Extended ──
  "cloud-off": icons.CloudOffIcon,
  "cloud_off": icons.CloudOffIcon,
  "cloud-snow": icons.CloudSnowIcon,
  "cloud-lightning": icons.CloudLightningIcon,
  "cloud-sun": icons.CloudSunIcon,
  "snowflake": icons.SnowflakeIcon,
  "ac_unit": icons.SnowflakeIcon,
  "rainbow": icons.RainbowIcon,
  "sunrise": icons.SunriseIcon,
  "sunset": icons.SunsetIcon,
  "umbrella": icons.UmbrellaIcon,
  "waves": icons.WavesIcon,
  "water": icons.WavesIcon,
  "tornado": icons.TornadoIcon,

  // ── Buildings ──
  "school-building": icons.SchoolIcon,
  "hospital": icons.HospitalIcon,
  "local_hospital": icons.HospitalIcon,
  "factory": icons.FactoryIcon,
  "warehouse": icons.WarehouseIcon,
  "landmark": icons.LandmarkIcon,
  "account_balance": icons.LandmarkIcon,
  "hotel": icons.HotelIcon,
  "library": icons.LibraryIcon,
  "local_library": icons.LibraryIcon,
  "church": icons.ChurchIcon,

  // ── Nature & Life ──
  "leaf": icons.LeafIcon,
  "eco": icons.LeafIcon,
  "tree-pine": icons.TreePineIcon,
  "park": icons.TreePineIcon,
  "flower": icons.FlowerIcon,
  "local_florist": icons.FlowerIcon,
  "mountain": icons.MountainIcon,
  "terrain": icons.MountainIcon,
  "bird": icons.BirdIcon,
  "paw-print": icons.PawPrintIcon,
  "pets": icons.PawPrintIcon,
  "feather": icons.FeatherIcon,
  "recycle": icons.RecycleIcon,
  "recycling": icons.RecycleIcon,

  // ── Food & Drink ──
  "pizza": icons.PizzaIcon,
  "local_pizza": icons.PizzaIcon,
  "cake": icons.CakeIcon,
  "cake_birthday": icons.CakeIcon,
  "utensils": icons.UtensilsIcon,
  "restaurant": icons.UtensilsIcon,
  "wine": icons.WineIcon,
  "wine_bar": icons.WineIcon,

  // ── Health & Medical ──
  "heart-pulse": icons.HeartPulseIcon,
  "monitor_heart": icons.HeartPulseIcon,
  "heart-crack": icons.HeartCrackIcon,
  "heart_broken": icons.HeartCrackIcon,
  "pill": icons.PillIcon,
  "medication": icons.PillIcon,
  "stethoscope": icons.StethoscopeIcon,
  "brain": icons.BrainIcon,
  "psychology": icons.BrainIcon,
  "ambulance": icons.AmbulanceIcon,
  "syringe": icons.SyringeIcon,
  "vaccines": icons.SyringeIcon,
  "bandage": icons.BandageIcon,

  // ── Commerce Extended ──
  "piggy-bank": icons.PiggyBankIcon,
  "savings": icons.PiggyBankIcon,
  "store": icons.StoreIcon,
  "storefront": icons.StoreIcon,
  "ticket": icons.TicketIcon,
  "confirmation_number": icons.TicketIcon,
  "barcode": icons.BarcodeIcon,

  // ── Development ──
  "git-branch": icons.GitBranchIcon,
  "git-commit": icons.GitCommitIcon,
  "git-merge": icons.GitMergeIcon,
  "git-pull-request": icons.GitPullRequestIcon,
  "git-fork": icons.GitForkIcon,
  "variable": icons.VariableIcon,
  "braces": icons.BracesIcon,
  "data_object": icons.BracesIcon,
  "brackets": icons.BracketsIcon,
  "data_array": icons.BracketsIcon,
  "webhook": icons.WebhookIcon,
  "binary": icons.BinaryIcon,

  // ── Shapes ──
  "circle": icons.CircleIcon,
  "square": icons.SquareIcon,
  "triangle": icons.TriangleIcon,
  "diamond": icons.DiamondIcon,
  "hexagon": icons.HexagonIcon,
  "octagon": icons.OctagonIcon,
  "pentagon": icons.PentagonIcon,
  "star-half": icons.StarHalfIcon,
  "star_half": icons.StarHalfIcon,

  // ── Text Formatting Extended ──
  "strikethrough": icons.StrikethroughIcon,
  "format_strikethrough": icons.StrikethroughIcon,
  "align-justify": icons.AlignJustifyIcon,
  "format_align_justify": icons.AlignJustifyIcon,
  "heading-1": icons.Heading1Icon,
  "heading-2": icons.Heading2Icon,
  "heading-3": icons.Heading3Icon,
  "quote": icons.QuoteIcon,
  "format_quote": icons.QuoteIcon,
  "indent": icons.IndentIcon,
  "format_indent_increase": icons.IndentIcon,
  "outdent": icons.OutdentIcon,
  "format_indent_decrease": icons.OutdentIcon,
  "subscript": icons.SubscriptIcon,
  "superscript": icons.SuperscriptIcon,
  "highlighter": icons.HighlighterIcon,
  "highlight": icons.HighlighterIcon,
  "wrap-text": icons.WrapTextIcon,
  "remove-formatting": icons.RemoveFormattingIcon,
  "format_clear": icons.RemoveFormattingIcon,
  "pen-tool": icons.PenToolIcon,

  // ── Math ──
  "infinity": icons.InfinityIcon,
  "all_inclusive": icons.InfinityIcon,
  "divide": icons.DivideIcon,
  "equal": icons.EqualIcon,
  "sigma": icons.SigmaIcon,
  "pi": icons.PiIcon,
  "square-root": icons.SquareRootIcon,

  // ── Misc Common ──
  "rotate-cw": icons.RotateCwIcon,
  "expand": icons.ExpandIcon,
  "open_in_full": icons.ExpandIcon,
  "shrink": icons.ShrinkIcon,
  "close_fullscreen": icons.ShrinkIcon,
  "focus": icons.FocusIcon,
  "center_focus_strong": icons.FocusIcon,
  "scan": icons.ScanIcon,
  "line-chart": icons.LineChartIcon,
  "show_chart": icons.LineChartIcon,
  "area-chart": icons.AreaChartIcon,
  "gauge": icons.GaugeIcon,
  "speed": icons.GaugeIcon,
  "presentation": icons.PresentationIcon,
  "slideshow": icons.PresentationIcon,
  "eye-dropper": icons.EyeDropperIcon,
  "colorize": icons.EyeDropperIcon,
  "hand": icons.HandIcon,
  "pan_tool": icons.HandIcon,
  "handshake": icons.HandshakeIcon,
  "languages": icons.LanguagesIcon,
  "translate": icons.LanguagesIcon,
  "ship": icons.ShipIcon,
  "directions_boat": icons.ShipIcon,
  "bike": icons.BikeIcon,
  "directions_bike": icons.BikeIcon,
  "fuel": icons.FuelIcon,
  "local_gas_station": icons.FuelIcon,
  "locate": icons.LocateIcon,
  "my_location": icons.LocateIcon,
  "signpost": icons.SignpostIcon,
  "road": icons.RoadIcon,
  "route": icons.RouteIcon,
  "tent": icons.TentIcon,
  "baby": icons.BabyIcon,
  "child_care": icons.BabyIcon,
  "gem": icons.GemIcon,
  "diamond_gem": icons.GemIcon,
  "package": icons.PackageIcon,
  "inventory_2": icons.PackageIcon,
  "newspaper": icons.NewspaperIcon,

  // ── Files Extended ──
  "file-code": icons.FileCodeIcon,
  "file-image": icons.FileImageIcon,
  "file-video": icons.FileVideoIcon,
  "file-archive": icons.FileArchiveIcon,
  "file-check": icons.FileCheckIcon,
  "file-x": icons.FileXIcon,
  "folder-plus": icons.FolderPlusIcon,
  "create_new_folder": icons.FolderPlusIcon,
  "folder-minus": icons.FolderMinusIcon,
  "folder-closed": icons.FolderClosedIcon,
  "folder-tree": icons.FolderTreeIcon,
  "account_tree": icons.FolderTreeIcon,

  // ── Communication Extended ──
  "mail-open": icons.MailOpenIcon,
  "mail-check": icons.MailCheckIcon,
  "mail-plus": icons.MailPlusIcon,
  "mail-x": icons.MailXIcon,
  "phone-call": icons.PhoneCallIcon,
  "phone_in_talk": icons.PhoneCallIcon,
  "phone-incoming": icons.PhoneIncomingIcon,
  "phone_callback": icons.PhoneIncomingIcon,
  "phone-outgoing": icons.PhoneOutgoingIcon,
  "phone_forwarded": icons.PhoneOutgoingIcon,
  "megaphone": icons.MegaphoneIcon,
  "campaign": icons.MegaphoneIcon,
  "user-x": icons.UserXIcon,
  "person_remove": icons.UserXIcon,
  "user-cog": icons.UserCogIcon,
  "manage_accounts": icons.UserCogIcon,

  // ── Calendar Extended ──
  "calendar-days": icons.CalendarDaysIcon,
  "event": icons.CalendarDaysIcon,
  "calendar-check": icons.CalendarCheckIcon,
  "event_available": icons.CalendarCheckIcon,
  "calendar-plus": icons.CalendarPlusIcon,
  "calendar-x": icons.CalendarXIcon,
  "event_busy": icons.CalendarXIcon,
  "alarm-clock": icons.AlarmClockIcon,
  "alarm": icons.AlarmClockIcon,

  // ── Sports & Games ──
  "puzzle": icons.PuzzleIcon,
  "extension": icons.PuzzleIcon,
  "gamepad": icons.GamepadIcon,
  "sports_esports": icons.GamepadIcon,
  "medal": icons.MedalIcon,
  "military_tech": icons.MedalIcon,
  "dumbbell": icons.DumbbellIcon,
  "fitness_center": icons.DumbbellIcon,
  "notebook": icons.NotebookIcon,
  "backpack": icons.BackpackIcon,
};

export { builtInIcons };
