import type { ComponentType } from "react";
import type { IconComponentProps } from "./icon-provider";
import * as icons from "./icons";

/**
 * Maps string names to built-in SVG icon components.
 * Supports both spark-ui names (kebab-case) and Material Symbols names (snake_case).
 */
const builtInIcons: Record<string, ComponentType<IconComponentProps>> = {
  // ── Navigation ──
  "chevron-left": icons.ChevronLeftIcon,
  "chevron_left": icons.ChevronLeftIcon,
  "chevron-right": icons.ChevronRightIcon,
  "chevron_right": icons.ChevronRightIcon,
  "chevron-down": icons.ChevronDownIcon,
  "chevron_down": icons.ChevronDownIcon,
  "expand_more": icons.ChevronDownIcon,
  "chevron-up": icons.ChevronUpIcon,
  "chevron_up": icons.ChevronUpIcon,
  "expand_less": icons.ChevronUpIcon,
  "chevrons-left": icons.ChevronsLeftIcon,
  "chevrons_left": icons.ChevronsLeftIcon,
  "first-page": icons.ChevronsLeftIcon,
  "first_page": icons.ChevronsLeftIcon,
  "chevrons-right": icons.ChevronsRightIcon,
  "chevrons_right": icons.ChevronsRightIcon,
  "last-page": icons.ChevronsRightIcon,
  "last_page": icons.ChevronsRightIcon,
  "chevrons-up-down": icons.ChevronsUpDownIcon,
  "chevrons_up_down": icons.ChevronsUpDownIcon,
  "unfold_more": icons.ChevronsUpDownIcon,
  "arrow-left": icons.ArrowLeftIcon,
  "arrow_left": icons.ArrowLeftIcon,
  "arrow-right": icons.ArrowRightIcon,
  "arrow_right": icons.ArrowRightIcon,
  "arrow_forward": icons.ArrowRightIcon,
  "arrow-up": icons.ArrowUpIcon,
  "arrow_up": icons.ArrowUpIcon,
  "arrow-down": icons.ArrowDownIcon,
  "arrow_down": icons.ArrowDownIcon,
  "external-link": icons.ExternalLinkIcon,
  "navigation": icons.NavigationIcon,

  // ── Actions ──
  "close": icons.CloseIcon,
  "x": icons.CloseIcon,
  "plus": icons.PlusIcon,
  "add": icons.PlusIcon,
  "minus": icons.MinusIcon,
  "check": icons.CheckIcon,
  "search": icons.SearchIcon,
  "edit": icons.EditIcon,
  "trash": icons.TrashIcon,
  "delete": icons.TrashIcon,
  "copy": icons.CopyIcon,
  "download": icons.DownloadIcon,
  "upload": icons.UploadIcon,
  "cloud_upload": icons.UploadIcon,
  "filter": icons.FilterIcon,
  "tune": icons.FilterIcon,
  "settings": icons.SettingsIcon,
  "settings-gear": icons.SettingsGearIcon,
  "more-horizontal": icons.MoreHorizontalIcon,
  "more_horiz": icons.MoreHorizontalIcon,
  "more-vertical": icons.MoreVerticalIcon,
  "more_vert": icons.MoreVerticalIcon,
  "refresh": icons.RefreshCwIcon,
  "refresh-cw": icons.RefreshCwIcon,
  "rotate-ccw": icons.RotateCcwIcon,
  "save": icons.SaveIcon,
  "scissors": icons.ScissorsIcon,
  "crop": icons.CropIcon,

  // ── Status ──
  "check-circle": icons.CheckCircleIcon,
  "check_circle": icons.CheckCircleIcon,
  "alert-circle": icons.AlertCircleIcon,
  "error": icons.AlertCircleIcon,
  "alert-triangle": icons.AlertTriangleIcon,
  "warning": icons.AlertTriangleIcon,
  "info": icons.InfoIcon,
  "x-circle": icons.XCircleIcon,
  "help-circle": icons.HelpCircleIcon,
  "plus-circle": icons.PlusCircleIcon,
  "minus-circle": icons.MinusCircleIcon,
  "slash": icons.SlashIcon,

  // ── Communication ──
  "phone": icons.PhoneIcon,
  "phone-off": icons.PhoneOffIcon,
  "message-square": icons.MessageSquareIcon,
  "message-circle": icons.MessageCircleIcon,
  "send": icons.SendIcon,
  "inbox": icons.InboxIcon,
  "at-sign": icons.AtSignIcon,
  "mail": icons.MailIcon,

  // ── Media ──
  "play": icons.PlayIcon,
  "pause": icons.PauseIcon,
  "stop-circle": icons.StopCircleIcon,
  "skip-forward": icons.SkipForwardIcon,
  "skip-back": icons.SkipBackIcon,
  "volume": icons.VolumeIcon,
  "volume-1": icons.Volume1Icon,
  "volume-2": icons.Volume2Icon,
  "volume-x": icons.VolumeXIcon,
  "mic": icons.MicIcon,
  "mic-off": icons.MicOffIcon,
  "video": icons.VideoIcon,
  "camera": icons.CameraIcon,
  "music": icons.MusicIcon,
  "image": icons.ImageIcon,

  // ── Files ──
  "file": icons.FileIcon,
  "file-text": icons.FileTextIcon,
  "file-plus": icons.FilePlusIcon,
  "folder": icons.FolderIcon,
  "folder-open": icons.FolderOpenIcon,
  "clipboard": icons.ClipboardIcon,
  "archive": icons.ArchiveIcon,
  "paperclip": icons.PaperclipIcon,
  "link": icons.LinkIcon,

  // ── Layout ──
  "menu": icons.MenuIcon,
  "grip-vertical": icons.GripVerticalIcon,
  "grip_vertical": icons.GripVerticalIcon,
  "drag_indicator": icons.GripVerticalIcon,
  "grid": icons.GridIcon,
  "list": icons.ListIcon,
  "columns": icons.ColumnsIcon,
  "sidebar": icons.SidebarIcon,
  "maximize": icons.MaximizeIcon,
  "minimize": icons.MinimizeIcon,
  "layers": icons.LayersIcon,

  // ── Commerce ──
  "shopping-cart": icons.ShoppingCartIcon,
  "shopping-bag": icons.ShoppingBagIcon,
  "credit-card": icons.CreditCardIcon,
  "dollar-sign": icons.DollarSignIcon,
  "gift": icons.GiftIcon,
  "percent": icons.PercentIcon,
  "tag": icons.TagIcon,

  // ── Maps ──
  "map-pin": icons.MapPinIcon,
  "map": icons.MapIcon,
  "compass": icons.CompassIcon,

  // ── Devices ──
  "smartphone": icons.SmartphoneIcon,
  "tablet": icons.TabletIcon,
  "monitor": icons.MonitorIcon,
  "laptop": icons.LaptopIcon,
  "printer": icons.PrinterIcon,

  // ── Security ──
  "lock": icons.LockIcon,
  "unlock": icons.UnlockIcon,
  "shield": icons.ShieldIcon,
  "shield-check": icons.ShieldCheckIcon,
  "key": icons.KeyIcon,
  "fingerprint": icons.FingerprintIcon,

  // ── Data ──
  "bar-chart": icons.BarChartIcon,
  "pie-chart": icons.PieChartIcon,
  "trending-up": icons.TrendingUpIcon,
  "trending-down": icons.TrendingDownIcon,
  "activity": icons.ActivityIcon,
  "database": icons.DatabaseIcon,
  "server": icons.ServerIcon,
  "hash": icons.HashIcon,

  // ── Formatting ──
  "bold": icons.BoldIcon,
  "italic": icons.ItalicIcon,
  "underline": icons.UnderlineIcon,
  "align-left": icons.AlignLeftIcon,
  "align-center": icons.AlignCenterIcon,
  "align-right": icons.AlignRightIcon,
  "type": icons.TypeIcon,

  // ── Social ──
  "share": icons.ShareIcon,
  "share-2": icons.Share2Icon,
  "thumbs-up": icons.ThumbsUpIcon,
  "thumbs-down": icons.ThumbsDownIcon,
  "bookmark": icons.BookmarkIcon,
  "flag": icons.FlagIcon,
  "award": icons.AwardIcon,

  // ── UI ──
  "calendar": icons.CalendarIcon,
  "calendar_today": icons.CalendarIcon,
  "eye": icons.EyeIcon,
  "visibility": icons.EyeIcon,
  "eye-off": icons.EyeOffIcon,
  "visibility_off": icons.EyeOffIcon,
  "home": icons.HomeIcon,
  "user": icons.UserIcon,
  "users": icons.UsersIcon,
  "user-plus": icons.UserPlusIcon,
  "user-minus": icons.UserMinusIcon,
  "user-check": icons.UserCheckIcon,
  "star": icons.StarIcon,
  "heart": icons.HeartIcon,
  "bell": icons.BellIcon,
  "notifications": icons.BellIcon,
  "loader": icons.LoaderIcon,
  "log-in": icons.LogInIcon,
  "log-out": icons.LogOutIcon,
  "logout": icons.LogOutIcon,
  "code": icons.CodeIcon,
  "terminal": icons.TerminalIcon,
  "target": icons.TargetIcon,
  "crosshair": icons.CrosshairIcon,
  "anchor": icons.AnchorIcon,
  "life-buoy": icons.LifeBuoyIcon,
  "sparkles": icons.SparklesIcon,

  // ── Weather ──
  "cloud": icons.CloudIcon,
  "cloud-rain": icons.CloudRainIcon,
  "thermometer": icons.ThermometerIcon,
  "wind": icons.WindIcon,
  "droplet": icons.DropletIcon,
  "sun": icons.SunIcon,
  "light_mode": icons.SunIcon,
  "moon": icons.MoonIcon,
  "dark_mode": icons.MoonIcon,

  // ── Time ──
  "clock": icons.ClockIcon,
  "watch": icons.WatchIcon,
  "timer": icons.TimerIcon,

  // ── Misc ──
  "zap": icons.ZapIcon,
  "battery": icons.BatteryIcon,
  "wifi": icons.WifiIcon,
  "bluetooth": icons.BluetoothIcon,
  "power": icons.PowerIcon,
  "globe": icons.GlobeIcon,

  // ── Additional Actions ──
  "undo": icons.UndoIcon,
  "redo": icons.RedoIcon,
  "cut": icons.ScissorsIcon,
  "zoom-in": icons.ZoomInIcon,
  "zoom_in": icons.ZoomInIcon,
  "zoom-out": icons.ZoomOutIcon,
  "zoom_out": icons.ZoomOutIcon,
  "move": icons.MoveIcon,
  "cursor": icons.CursorIcon,
  "mouse-pointer": icons.CursorIcon,
  "list-ordered": icons.ListOrderedIcon,
  "format_list_numbered": icons.ListOrderedIcon,
  "print": icons.PrinterIcon,

  // ── Material Symbols Formatting Aliases ──
  "format-bold": icons.BoldIcon,
  "format_bold": icons.BoldIcon,
  "format-italic": icons.ItalicIcon,
  "format_italic": icons.ItalicIcon,
  "format-underline": icons.UnderlineIcon,
  "format_underline": icons.UnderlineIcon,
  "format-align-left": icons.AlignLeftIcon,
  "format_align_left": icons.AlignLeftIcon,
  "format-align-center": icons.AlignCenterIcon,
  "format_align_center": icons.AlignCenterIcon,
  "format-align-right": icons.AlignRightIcon,
  "format_align_right": icons.AlignRightIcon,

  // ── Material Symbols Misc Aliases ──
  "drafts": icons.FileTextIcon,
  "publish": icons.SendIcon,
  "schedule": icons.ClockIcon,
  "delete_forever": icons.TrashIcon,
  "picture_as_pdf": icons.FileTextIcon,
  "table_chart": icons.GridIcon,

  // ── Extended Arrows & Navigation ──
  "arrow-up-left": icons.ArrowUpLeftIcon,
  "arrow_up_left": icons.ArrowUpLeftIcon,
  "arrow-up-right": icons.ArrowUpRightIcon,
  "arrow_up_right": icons.ArrowUpRightIcon,
  "arrow-down-left": icons.ArrowDownLeftIcon,
  "arrow_down_left": icons.ArrowDownLeftIcon,
  "arrow-down-right": icons.ArrowDownRightIcon,
  "arrow_down_right": icons.ArrowDownRightIcon,
  "arrow-left-right": icons.ArrowLeftRightIcon,
  "arrow_left_right": icons.ArrowLeftRightIcon,
  "swap_horiz": icons.ArrowLeftRightIcon,
  "arrow-up-down": icons.ArrowUpDownIcon,
  "arrow_up_down": icons.ArrowUpDownIcon,
  "swap_vert": icons.ArrowUpDownIcon,
  "corner-down-left": icons.CornerDownLeftIcon,
  "corner-down-right": icons.CornerDownRightIcon,
  "corner-up-left": icons.CornerUpLeftIcon,
  "corner-up-right": icons.CornerUpRightIcon,
  "chevrons-down": icons.ChevronsDownIcon,
  "chevrons_down": icons.ChevronsDownIcon,
  "chevrons-up": icons.ChevronsUpIcon,
  "chevrons_up": icons.ChevronsUpIcon,
  "arrow-big-up": icons.ArrowBigUpIcon,
  "arrow-big-down": icons.ArrowBigDownIcon,
  "arrow-big-left": icons.ArrowBigLeftIcon,
  "arrow-big-right": icons.ArrowBigRightIcon,
  "move-horizontal": icons.MoveHorizontalIcon,
  "move-vertical": icons.MoveVerticalIcon,
  "move-diagonal": icons.MoveDiagonalIcon,
  "repeat": icons.RepeatIcon,
  "repeat-1": icons.Repeat1Icon,
  "repeat_one": icons.Repeat1Icon,

  // ── Extended Actions & Editing ──
  "paste": icons.PasteIcon,
  "content_paste": icons.PasteIcon,
  "clipboard-check": icons.ClipboardCheckIcon,
  "clipboard_check": icons.ClipboardCheckIcon,
  "assignment_turned_in": icons.ClipboardCheckIcon,
  "clipboard-copy": icons.ClipboardCopyIcon,
  "clipboard-list": icons.ClipboardListIcon,
  "clipboard_list": icons.ClipboardListIcon,
  "clipboard-x": icons.ClipboardXIcon,
  "trash-2": icons.Trash2Icon,
  "archive-restore": icons.ArchiveRestoreIcon,
  "unarchive": icons.ArchiveRestoreIcon,
  "eraser": icons.EraserIcon,
  "wand": icons.WandIcon,
  "auto_fix_high": icons.WandIcon,
  "magic-wand": icons.WandIcon,
  "pin": icons.PinIcon,
  "push_pin": icons.PinIcon,
  "pin-off": icons.PinOffIcon,
  "sort-asc": icons.SortAscIcon,
  "sort_ascending": icons.SortAscIcon,
  "sort-desc": icons.SortDescIcon,
  "sort_descending": icons.SortDescIcon,
  "arrow-down-az": icons.ArrowDownAZIcon,
  "sort_by_alpha": icons.ArrowDownAZIcon,
  "arrow-up-az": icons.ArrowUpAZIcon,

  // ── Extended Status & Feedback ──
  "ban": icons.BanIcon,
  "block": icons.BanIcon,
  "do_not_disturb": icons.BanIcon,
  "circle-alert": icons.CircleAlertIcon,
  "circle-check": icons.CircleCheckIcon,
  "task_alt": icons.CircleCheckIcon,
  "octagon-alert": icons.OctagonAlertIcon,
  "shield-alert": icons.ShieldAlertIcon,
  "shield-x": icons.ShieldXIcon,
  "check-check": icons.CheckCheckIcon,
  "done_all": icons.CheckCheckIcon,
  "circle-dot": icons.CircleDotIcon,
  "radio_button_checked": icons.CircleDotIcon,
  "circle-dashed": icons.CircleDashedIcon,
  "badge-check": icons.BadgeCheckIcon,
  "verified": icons.BadgeCheckIcon,

  // ── Bell Variants ──
  "bell-off": icons.BellOffIcon,
  "notifications_off": icons.BellOffIcon,
  "bell-ring": icons.BellRingIcon,
  "notifications_active": icons.BellRingIcon,
  "bell-dot": icons.BellDotIcon,
  "notification_important": icons.BellDotIcon,
  "bell-plus": icons.BellPlusIcon,
  "bell-minus": icons.BellMinusIcon,

  // ── Layout & Panels ──
  "panel-left": icons.PanelLeftIcon,
  "panel-left-open": icons.PanelLeftOpenIcon,
  "panel-left-close": icons.PanelLeftCloseIcon,
  "panel-right": icons.PanelRightIcon,
  "panel-right-open": icons.PanelRightOpenIcon,
  "panel-right-close": icons.PanelRightCloseIcon,
  "panel-top": icons.PanelTopIcon,
  "panel-bottom": icons.PanelBottomIcon,
  "layout-dashboard": icons.LayoutDashboardIcon,
  "dashboard": icons.LayoutDashboardIcon,
  "layout-grid": icons.LayoutGridIcon,
  "layout-list": icons.LayoutListIcon,
  "layout-template": icons.LayoutTemplateIcon,
  "kanban": icons.KanbanIcon,
  "view_kanban": icons.KanbanIcon,
  "table": icons.TableIcon,
  "table_view": icons.TableIcon,
  "sticky-note": icons.StickyNoteIcon,
  "note": icons.StickyNoteIcon,
  "grip-horizontal": icons.GripHorizontalIcon,
  "drag_handle": icons.GripHorizontalIcon,
  "separator-horizontal": icons.SeparatorHorizontalIcon,
  "separator-vertical": icons.SeparatorVerticalIcon,
  "resize": icons.ResizeIcon,
  "split": icons.SplitIcon,
  "call_split": icons.SplitIcon,
  "app-window": icons.AppWindowIcon,
  "web_asset": icons.AppWindowIcon,
  "picture-in-picture": icons.PictureInPictureIcon,
  "pip": icons.PictureInPictureIcon,

  // ── Form Controls ──
  "toggle-left": icons.ToggleLeftIcon,
  "toggle_off": icons.ToggleLeftIcon,
  "toggle-right": icons.ToggleRightIcon,
  "toggle_on": icons.ToggleRightIcon,
  "sliders-horizontal": icons.SlidersHorizontalIcon,
  "tune_horizontal": icons.SlidersHorizontalIcon,
  "sliders-vertical": icons.SlidersVerticalIcon,
  "text-cursor": icons.TextCursorIcon,
  "text-cursor-input": icons.TextCursorInputIcon,
  "square-check": icons.SquareCheckIcon,
  "check_box": icons.SquareCheckIcon,
  "list-filter": icons.ListFilterIcon,
  "filter_list": icons.ListFilterIcon,
};

export { builtInIcons };
